preconnect:
  - https://gcore.jsdelivr.net
  - https://unpkg.com
  - https://cdn.jsdelivr.net
  - https://cdnjs.cloudflare.com
  - https://jsd.dusays.com
logo:
  avatar: '[https://cdn.dusays.com/favicon.ico](/about/)'
  title: '[{config.title}](/)'
  subtitle: 'dusays.com'
menubar:
  items:
    - id: post
      theme: '#1BCDFC'
      icon: solar:documents-bold-duotone
      title: 博客
      url: /
    - id: wiki
      theme: '#3DC550'
      icon: solar:notebook-bookmark-bold-duotone
      title: 图床
      url: https://7bu.top/
    - id: explore
      theme: '#FA6400'
      icon: solar:planet-bold-duotone
      title: 开往
      url: https://www.travellings.cn/go.html
    - id: social
      theme: '#F44336'
      icon: solar:chat-square-like-bold-duotone
      title: 聊天
      url: https://chat.dusays.com/signup_user_complete/?id=pmsp46j6ji8xdpket1pohptpnr&md=link&sbr=fa
site_tree:
  home:
    leftbar: welcome, sylj, recent
    rightbar: sjtp, recent_comments, sffw, qbtc, ltgc, mmtg
    comments:
  index_blog:
    base_dir: blog
    menu_id: post
    leftbar: welcome, recent
    rightbar: qbtc, ltgc, mmtg
    nav_tabs:
  index_topic:
    base_dir: topic
    menu_id: post
  index_wiki:
    base_dir: wiki
    menu_id: wiki
    leftbar: related, recent
    rightbar:
    nav_tabs:
  post:
    menu_id: post
    leftbar: wezh, welcome, related, recent
    rightbar: ghrepo, toc, recent_comments, sffw, qbtc, ltgc, mmtg, sjtp
  topic:
    menu_id: post
  wiki:
    menu_id: wiki
    leftbar: tree, related, recent
    rightbar: ghrepo, toc
  notebooks:
    base_dir: notebooks
    menu_id: notebooks
    leftbar: recent
    rightbar: null
  notes:
    menu_id: notebooks
    leftbar: tagtree, recent
    rightbar: null
  note:
    leftbar: tagtree, recent
    rightbar: toc
  author:
    base_dir: author
    menu_id: post
    leftbar: recent, timeline
    rightbar: timeline
  error_page:
    menu_id: post
    '404': '/404.html'
    leftbar: recent, timeline
    rightbar: timeline
  page:
    leftbar: recent
    rightbar: toc
article:
  pin_style: flat
  type: tech
  indent:
  cover_ratio: 2
  banner_ratio: 2.5
  auto_banner: false
  auto_excerpt: 128
  category_color:
    '探索号': '#f44336'
  license: '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans) 许可协议，转载请注明出处。</br><iframe src="https://cdn.dusays.com/drinks/" style="overflow-x:hidden;overflow-y:hidden; border:0xp none #fff; min-height:240px; width:100%;"  frameborder="0" scrolling="no"></iframe>'
  share:
  related_posts:
    enable: false
    max_count: 5
comments:
  service: artalk
  comment_title: 快来参与讨论吧~
  custom_css:
  beaudar:
    repo: xxx/xxx
    issue-term: pathname
    issue-number:
    theme: preferred-color-scheme
    label:
    input-position: top
    comment-order: desc
    keep-theme:
    loading: false
    branch: main
  utterances:
    repo: xxx/xxx
    issue-term: pathname
    issue-number:
    theme: preferred-color-scheme
    label:
  giscus:
    src: https://giscus.app/client.js
    data-repo: xxx/xxx
    data-repo-id:
    data-category:
    data-category-id:
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading:
    crossorigin: anonymous
  twikoo:
    js: https://jsd.dusays.com/npm/twikoo@1.6/dist/twikoo.all.min.js
    envId: https://xxx
  waline:
    js: https://jsd.dusays.com/npm/@waline/client@3.1/dist/waline.js
    css: https://jsd.dusays.com/npm/@waline/client@3.1/dist/waline.css
    meta_css: https://jsd.dusays.com/npm/@waline/client@3.1/dist/waline-meta.css
    serverURL: https://waline.vercel.app
    commentCount: true
    pageview: false
  artalk:
    css: https://artalk.dusays.com/dist/Artalk.css
    js: https://artalk.dusays.com/dist/Artalk.js
    server: https://artalk.dusays.com
    site: '杜老师说'
    darkMode: auto
    imageUploader:
      api: 'https://7bu.top/api/v1/upload'
      token: 'Bearer 198|G3L9heu8LimK9YSaQzFwqGlfv6EhYTHVIOIcGzUX'
      resp: 'data.links.url'
footer:
  social:
    github:
      icon: '<img src="https://jsd.admincdn.com/npm/dusays@5.0.0/020-rss.svg"/>'
      url: https://dusays.com/atom.xml
    unsplash:
      icon: '<img src="https://jsd.admincdn.com/npm/dusays@5.0.0/031-twitch.svg"/>'
      url: https://a.dusays.com/
    comments:
      icon: '<img src="https://jsd.admincdn.com/npm/dusays@5.0.0/033-spotify.svg"/>'
      url: https://dusays.com/baidusitemap.xml
    theme:
      icon: solar:sunny-outline
      onclick: 'switchTheme()'
  sitemap:
    - title: 跳转
      items:
        - '[十年虫洞](https://www.foreverblog.cn/go.html)'
        - ''
        - ''
        - '[异次元之旅](https://travel.moe/go.html?travel=on)'
        - ''
        - ''
        - '[本站总访客数 <span id="busuanzi_site_uv"></span> 人](https://bsz.dusays.com/)'
        - ''
        - ''
        - '[本站总访问量 <span id="busuanzi_site_pv"></span> 次](https://bsz.dusays.com/)'
    - title: 声明
      items:
        - '<a href="https://dusays.com/7bu/" target="_blank"><img src="https://jsd.admincdn.com/npm/dusays@5.0.0/7bu.svg" width="110" height="20"/></a>'
        - '<a href="https://dusays.com/yinsi/" target="_blank"><img src="https://jsd.admincdn.com/npm/dusays@5.0.0/yinsi.svg" width="110" height="20"/></a>'
        - '<a href="https://dusays.com/mianze/" target="_blank"><img src="https://jsd.admincdn.com/npm/dusays@5.0.0/mianze.svg" width="110" height="20"/></a>'
        - '<a href="https://dusays.com/says/" target="_blank"><img src="https://jsd.admincdn.com/npm/dusays@5.0.0/says.svg" width="110" height="20"/></a>'
    - title: 备案
      items:
        - '<a href="https://icp.gov.moe/?keyword=20229624" target="_blank"><img src="https://jsd.admincdn.com/npm/dusays@5.0.3/meng.svg" width="135" height="20"/></a>'
        - '<a href="https://beian.miit.gov.cn/" target="_blank"><img src="https://jsd.admincdn.com/npm/dusays@5.0.0/icp.svg" width="138" height="20"/></a>'
        - '<a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=21080402111261" target="_blank"><img src="https://jsd.admincdn.com/npm/dusays@5.0.0/liao.svg" width="174" height="20"/></a>'
        - '<a href="https://dusays.com/" target="_blank"><img src="https://jsd.admincdn.com/npm/dusays@5.0.0/copyright.svg" width="198" height="20"/></a>'
  content: |
    本站由 [{author.name}](/) 使用 [{theme.name} {theme.version}]({theme.tree}) 主题创建。<script async src="https://jsd.dusays.com/npm/penndu@16.0.0/bsz.js"></script>
    本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans) 许可协议，转载请注明出处。
    </br>
    [辛未羊的网络日志](https://panqiincs.me/) | [obaby@mars](https://zhongxiaojie.com/) | [codeqihan的博客](https://www.codeqihan.com/) | [乙未博客](https://yvii.cn/) | [晓雨杂记](https://lihaoyu.cn/) | [龙鲲博客](https://lklog.cn/) | [joojenZhou个人网站](https://joojen.com/) | [雾非雾](https://www.941741.xyz/) | [xaoxuu](https://xaoxuu.com/) | [晚夜的个人博客](https://www.iczrx.cn/)
tag_plugins:
  note:
    default_color: ''
    border: true
  checkbox:
    interactive: false
  quot:
    default:
      prefix: bxs:quote-left
      suffix: bxs:quote-right
    hashtag:
      prefix: solar:hashtag-square-bold
    question:
      prefix: ph:seal-question-fill
  emoji:
    default: https://jsd.dusays.com/gh/cdn-x/emoticons@3.1/qq/{name}.gif
    twemoji: https://jsd.dusays.com/gh/twitter/twemoji/assets/svg/{name}.svg
    qq: https://jsd.dusays.com/gh/cdn-x/emoticons@3.1/qq/{name}.gif
    aru: https://jsd.dusays.com/gh/cdn-x/emoticons@3.1/aru/{name}.gif
    tieba: https://jsd.dusays.com/gh/cdn-x/emoticons@3.1/tieba/{name}.png
    blobcat: https://jsd.dusays.com/gh/cdn-x/emoticons@3.1/blobcat/{name}.gif
  icon:
    default_color: accent
  button:
    default_color: theme
  image:
    parse_markdown: false
  copy:
    toast: 复制成功
  timeline:
    max-height: 80vh
  mark:
    default_color: yellow
  hashtag:
    default_color:
  okr:
    border: true
    status:
      in_track:
        color: blue
        label: 正常
      at_risk:
        color: yellow
        label: 风险
      off_track:
        color: orange
        label: 延期
      finished:
        color: green
        label: 已完成
      unfinished:
        color: red
        label: 未完成
  gallery:
    layout: grid
    size: mix
    ratio: square
  chat:
    api: https://siteinfo.listentothewind.cn/api/v1
dependencies:
  marked: https://jsd.dusays.com/npm/marked@18.0/lib/marked.umd.min.js
  lazyload:
    js: https://jsd.dusays.com/npm/vanilla-lazyload@19.1/dist/lazyload.min.js
    transition: fade
    fix_ratio: true
plugins:
  preload:
    enable: true
    service: flying_pages
    flying_pages: https://jsd.dusays.com/npm/flying-pages@2/flying-pages.min.js
  fancybox:
    enable: true
    mode: auto
    js: https://jsd.dusays.com/npm/@fancyapps/ui@6.1/dist/fancybox/fancybox.umd.js
    css: https://jsd.dusays.com/npm/@fancyapps/ui@6.1/dist/fancybox/fancybox.css
    selector: .timenode p>img
  swiper:
    enable: true
    css: https://jsd.dusays.com/npm/swiper@14.0/swiper-bundle.min.css
    js: https://jsd.dusays.com/npm/swiper@14.0/swiper-bundle.min.js
  scrollreveal:
    enable: true
    js: https://jsd.dusays.com/npm/scrollreveal@4.0/dist/scrollreveal.min.js
    distance: 8px
    duration: 1000
    interval: 100
    scale: 1
  tianli_gpt:
    enable:
    js: https://jsd.dusays.com/gh/qxchuckle/Post-Summary-AI@6.0/chuckle-post-ai.min.js
    field: post
    key: 5Q5mpqRK5DkwT1X9Gi5e
    total_length: 1000
    typewriter: true
    summary_directly: true
    rec_method: all
    hide_shuttle: true
    summary_toggle: false
    interface:
      name: AI摘要
      introduce: '我是文章辅助AI: QX-AI，点击下方的按钮，让我生成本文简介、推荐相关文章等。'
      version: TianliGPT
      button: ["介绍自己", "推荐文章", "生成摘要", "矩阵穿梭"]
  katex:
    enable:
    inject: |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.23/dist/katex.min.css" integrity="sha384-//SZkxyB7axjCAopkAL1E1rve+ZSPKapD89Lo/lLhcsXR+zOYl5z6zJZEFXil+q0" crossorigin="anonymous">
  mathjax:
    v3: false
    enable:
    js: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  mermaid:
    enable:
    style_optimization: false
    js: https://jsd.dusays.com/npm/mermaid@11/dist/mermaid.min.js
    theme: neutral
  copycode:
    enable: true
    default_text: 'Copy'
    success_text: 'Copied'
    toast: 复制成功
  heti:
    enable: false
    css: https://jsd.dusays.com/npm/heti@0.9/umd/heti.min.css
    js: https://jsd.dusays.com/npm/heti@0.9/umd/heti-addon.min.js
style:
  prefers_theme: auto
  font-size:
    root: 16px
    body: 17px
    code: 85%
    codeblock: 0.8125rem
  font-family:
    body: 'system-ui, "Microsoft Yahei", "Segoe UI", Arial, sans-serif'
    code: 'Menlo, Monaco, Consolas, system-ui, monospace, sans-serif'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, monospace, sans-serif'
  text-align: left
  prefix:
    h2: https://api.iconify.design/ci:heading-h2.svg
  border-radius:
    card-l: 24px
    card: 16px
    card-s: 12px
    bar: 12px
    image-l: 24px
    image: 16px
    image-s: 8px
  corner-shape: superellipse(1.5)
  color:
    theme: 'hsl(192 98% 55%)'
    accent: 'hsl(14 100% 57%)'
    link: 'hsl(207 90% 54%)'
  animated_avatar:
    animate: auto
  codeblock:
    scrollbar: 4px
    highlightjs_theme: https://jsd.dusays.com/gh/highlightjs/cdn-release@11.9/build/styles/atom-one-dark.min.css
  loading:
    loading: 正在加载
    error: 加载失败，请稍后重试。
  gradient:
    start: 'linear-gradient(to right, hsl(215, 95%, 64%), hsl(195, 95%, 60%), hsl(165, 95%, 56%), hsl(165, 95%, 56%), hsl(195 95% 60%), hsl(215, 95%, 64%))'
    searchbar: 'linear-gradient(to right, #04f3ff, #08ffc6, #ddf730, #ffbd19, #ff1fe0, #c418ff, #3b5bff, #04f3ff)'
    avatar: 'conic-gradient(from 0deg, #04f3ff, #08ffc6, #ddf730, #ffbd19, #ff1fe0, #c418ff, #3b5bff, #04f3ff)'
    angle: 210deg
  leftbar:
    ui-style: card
    background-color-light: var(--card)
    background-color-dark: var(--card)
    background-image: url(https://jsd.dusays.com/gh/cdn-x/placeholder@1.0.13/image/sidebar-bg1@small.jpg)
    blur-px: 100px
    blur-bg: var(--bg-a60)
    background-opacity: 0.8
  error_page: https://jsd.dusays.com/gh/cdn-x/placeholder@1.0.12/404/1c830bfcd517d.svg
  site:
    blur-px: 100px
    blur-bg: var(--bg-a75)
    blur-sat: 300%
  header_prefix:
    h2: '#'
    h3: '='
    h4: '|'
    h5: ':'
default:
  avatar: https://jsd.dusays.com/gh/cdn-x/placeholder@1.0.12/avatar/round/3442075.svg
  link: https://jsd.dusays.com/gh/cdn-x/placeholder@1.0.12/link/8f277b4ee0ecd.svg
  cover: https://jsd.dusays.com/gh/cdn-x/placeholder@1.0.12/cover/76b86c0226ffd.svg
  image: https://jsd.dusays.com/gh/cdn-x/placeholder@1.0.12/image/2659360.svg
  project: https://jsd.dusays.com/gh/cdn-x/placeholder@1.0.12/image/2779789.png
  banner: https://jsd.dusays.com/gh/cdn-x/placeholder@1.0.12/banner/books.jpg
  topic: https://jsd.dusays.com/gh/cdn-x/placeholder@1.0.12/image/10433048.png
  loading: https://api.iconify.design/eos-icons:three-dots-loading.svg?color=%231cd0fd
  image_onerror: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='2rem' height='2rem' viewBox='0 0 24 24'%3E%3C!-- Icon from Solar by 480 Design - https://creativecommons.org/licenses/by/4.0/ --%3E%3Cpath fill='%23F44336' d='M22 12.698c-.002 1.47-.013 2.718-.096 3.743c-.097 1.19-.296 2.184-.74 3.009a4.2 4.2 0 0 1-.73.983c-.833.833-1.893 1.21-3.237 1.39C15.884 22 14.2 22 12.053 22h-.106c-2.148 0-3.83 0-5.144-.177c-1.343-.18-2.404-.557-3.236-1.39c-.738-.738-1.12-1.656-1.322-2.795c-.2-1.12-.236-2.512-.243-4.241Q1.999 12.737 2 12v-.054c0-2.148 0-3.83.177-5.144c.18-1.343.557-2.404 1.39-3.236s1.893-1.21 3.236-1.39c1.168-.157 2.67-.175 4.499-.177a.697.697 0 1 1 0 1.396c-1.855.002-3.234.018-4.313.163c-1.189.16-1.906.464-2.436.994S3.72 5.8 3.56 6.99C3.397 8.2 3.395 9.788 3.395 12v.784l.932-.814a2.14 2.14 0 0 1 2.922.097l3.99 3.99a1.86 1.86 0 0 0 2.385.207l.278-.195a2.79 2.79 0 0 1 3.471.209l2.633 2.37c.265-.557.423-1.288.507-2.32c.079-.972.09-2.152.091-3.63a.698.698 0 0 1 1.396 0' opacity='.5'/%3E%3Cpath fill='%23F44336' fill-rule='evenodd' d='M17.5 11c-2.121 0-3.182 0-3.841-.659S13 8.621 13 6.5s0-3.182.659-3.841S15.379 2 17.5 2s3.182 0 3.841.659S22 4.379 22 6.5s0 3.182-.659 3.841S19.621 11 17.5 11m-1.47-7.03a.75.75 0 1 0-1.06 1.06l1.47 1.47l-1.47 1.47a.75.75 0 0 0 1.06 1.06l1.47-1.47l1.47 1.47a.75.75 0 1 0 1.06-1.06L18.56 6.5l1.47-1.47a.75.75 0 0 0-1.06-1.06L17.5 5.44z' clip-rule='evenodd'/%3E%3C/svg%3E"
