name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '16.17'
    - name: npm
      run: |
        npm i -g hexo-cli
        npm i
    - name: hexo
      run: |
        hexo g
        hexo algolia
        gulp
    - name: Deploy to Tencent CloudBase
      uses: TencentCloudBase/cloudbase-action@v2.0.1
      with:
        secretId: ${{secrets.secretId}}
        secretKey: ${{secrets.secretKey}}
        envId: ${{secrets.envId}}
