name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: npm
      run: |
        npm i -g hexo-cli
        npm i
    - name: hexo g
      run: hexo g
    - name: Deploy to Tencent CloudBase
      uses: TencentCloudBase/cloudbase-action@v2.0.1
      with:
        secretId: AKIDP978CsdmxnwatTMpFkhyo8P585DikM1D
        secretKey: 1FPdSPyniDCLlN9UgOFJjWtjHGz0Qq26
        envId: my-website-7g0jxmhka91e53cb
        staticSrcPath: ./public
